# For parameter descriptions, please refer to the template parameter files for each node.
ekf_localization_node:
  frequency: 10
  sensor_timeout: 0.1
  two_d_mode: true
  transform_time_offset: 0.0
  transform_timeout: 0.1
  print_diagnostics: true
  debug: false

  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom # GNSSやmcl_3dを使うため
  publish_tf: true

  odom0: /odometry/gps
  odom0_config: [true, true,  false, # x, y, z 位置
                 false, false, false, # 回転
                 false, false, false, # 速度
                 false, false, false, # 角速度
                 false, false, false] # 加速度
  odom0_queue_size: 10
  odom0_nodelay: false
  odom0_differential: false
  odom0_relative: false
  odom0_rejection_threshold: 1

  odom1: /whill/odom
  odom1_config: [true, true, false, # x, y, z 位置
                 false, false, true, # 回転
                 true, false, false, # 速度
                 false, false, true, # 角速度
                 false, false, false] # 加速度
  odom1_queue_size: 10
  odom1_nodelay: false
  odom1_differential: true
  odom1_relative: false
  odom1_rejection_threshold: 2

  pose0: /amcl_pose
  pose0_config: [false, false, false,
                 false, false, false,
                 true,  true,  true,
                 false, false, true,
                 false, false, false]
  pose0_queue_size: 50
  pose0_nodelay: false
  pose0_differential: false 
  pose0_relative: false

  imu0: /wit/imu
  imu0_config: [false, false,  false, # x, y, z 位置
                false, false, false, # 回転
                false, false, false, # 速度
                false, false, true, # 角速度
                false, false, false] # 加速度
  imu0_queue_size: 50 
  imu0_remove_gravitational_acceleration: true

  use_control: false
  #x, y, z, roll, pitch, yaw, vel x, vel y, vel z, vel roll, vel pitch, vel yaw, acc x, acc y, acc z
  process_noise_covariance: [0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x
                             0, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # y
                             0, 0, 1e-3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # z
                             0, 0, 0, 1e-2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # roll
                             0, 0, 0, 0, 1e-2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # pitch
                             0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, # yaw
                             0, 0, 0, 0, 0, 0, 1e-2, 0, 0, 0, 0, 0, 0, 0, 0, # vel x
                             0, 0, 0, 0, 0, 0, 0, 1e-2, 0, 0, 0, 0, 0, 0, 0, # vel y
                             0, 0, 0, 0, 0, 0, 0, 0, 1e-2, 0, 0, 0, 0, 0, 0, # vel z
                             0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-2, 0, 0, 0, 0, 0, # vel roll
                             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-2, 0, 0, 0, 0, # vel pitch
                             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, # vel yaw
                             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-2, 0, 0, # acc x
                             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-2, 0, # acc y
                             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-2] # acc z

  initial_estimate_covariance: [1e-2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # x
                                0, 1e-2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # y
                                0, 0, 1e-2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # z
                                0, 0, 0, 1e-2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # roll
                                0, 0, 0, 0, 1e-2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # pitch
                                0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, # yaw
                                0, 0, 0, 0, 0, 0, 1e-2, 0, 0, 0, 0, 0, 0, 0, 0, # vel x
                                0, 0, 0, 0, 0, 0, 0, 1e-2, 0, 0, 0, 0, 0, 0, 0, # vel y
                                0, 0, 0, 0, 0, 0, 0, 0, 1e-2, 0, 0, 0, 0, 0, 0, # vel z
                                0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-2, 0, 0, 0, 0, 0, # vel roll
                                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-2, 0, 0, 0, 0, # vel pitch
                                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, # vel yaw
                                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-2, 0, 0, # acc x
                                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-2,0, # acc y
                                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-2] # acc z

