mcl_3dl:
  map_frame: "map"
  odom_frame: "odom"
  fake_odom: false
  accum_cloud: 5
  num_particles: 256
  resample_var_x: 0.2
  resample_var_y: 0.2
  resample_var_z: 1.0
  bias_var_dist: 100.0
  lpf_step: 5.0
  dist_weight_z: 2.0
  likelihood:
    match_dist_min: 0.5
    match_output_dist: 0.3