planners:
  - name: NavfnROS
    type: navfn/NavfnROS

controllers:
  - name: DWAPlannerROS
    type: dwa_local_planner/DWAPlannerROS

controller_frequency: 30.0
controller_patience: 15.0

planner_frequency: 2.0
planner_patience: 15.0

oscillation_timeout: 10.0
oscillation_distance: 0.2