obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.95, -0.40], [-0.35, -0.45], [-0.35, 0.45],[0.95, 0.40]]
#footprint: [[1.00, -0.50], [-0.4, -0.5], [-0.4, 0.5],[1.00, 0.50]]
inflation_radius: 0.1 #0.2
transform_tolerance: 0.5
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: tim_scan, marking: true, clearing: true}

